name: Volcanic Pixels Typekit
version: "1.0"
description: Advanced Typekit integration for your WordPress blog
author: Daniel Chatfield
contributors: volcanicpixels
tags: 'typekit'
license: GPLv2
class_namespace: Volcanic_Pixels_Typekit